/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.67
 * Generated at: 2015-12-25 02:23:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.membership;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class agree_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/inc/header1.jsp", out, true);
      out.write("\r\n");
      out.write("<title>회원서비스 &gt; 회원가입&gt; 약관동의</title>\r\n");
      out.write("<script> \r\n");
      out.write("\r\n");
      out.write("function test(){ \r\n");
      out.write("\t if(testCheck()) // testCheck 펑션에서 리턴값이 참 , 거짓에 판단하여 다음 로직 GOGO \r\n");
      out.write("\t document.agree.submit();\r\n");
      out.write("\t} \r\n");
      out.write("\r\n");
      out.write("\tfunction testCheck(){ \r\n");
      out.write("\t var chckType = document.getElementsByName(\"agree\"); \r\n");
      out.write("\t for(i = 0; i < chckType.length; i++){ \r\n");
      out.write("\t if (chckType[i].checked == false){ \r\n");
      out.write("\t alert(\"약관을 체크해주세요\"); \r\n");
      out.write("\treturn false; \r\n");
      out.write("\t } \r\n");
      out.write("\t } \r\n");
      out.write("\r\n");
      out.write("\t return true;\r\n");
      out.write("\t} \r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("</script> \r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/inc/header2.jsp", out, true);
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"sub\">\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/inc/header2_1.jsp", out, true);
      out.write("\r\n");
      out.write("   <!-- gnb -->\r\n");
      out.write(" ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/inc/gnb.jsp", out, true);
      out.write(" \r\n");
      out.write("   <!-- //gnb -->\r\n");
      out.write("\r\n");
      out.write("      <hr />\r\n");
      out.write("\r\n");
      out.write("   <!-- containerG_w -->\r\n");
      out.write("   <div id=\"containerG_w\" class=\"sub01\">      \r\n");
      out.write("     \r\n");
      out.write("      <!-- contentG -->\r\n");
      out.write("      <div id=\"contentG\">\r\n");
      out.write("\r\n");
      out.write("         <!-- 본문영역 -->\r\n");
      out.write("         <div id=\"contentG_w\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <!-- 내용 -->\r\n");
      out.write("\r\n");
      out.write("<div>\r\n");
      out.write("<div>\r\n");
      out.write("\r\n");
      out.write("<ul>\r\n");
      out.write("    <li><a href=\"#tit01\">1. 제1장 총 칙</a></li>\r\n");
      out.write("    <li>- 제 1 조 목적</li>\r\n");
      out.write("    <li>- 제 2 조 적용범위</li>\r\n");
      out.write("    <li>- 제 3 조 용어의 정의</li>\r\n");
      out.write("    <li><a href=\"#tit02\">2. 제2장 자율준수관리자</a></li>\r\n");
      out.write("    <li>- 제 4 조 선임과 해임</li>\r\n");
      out.write("    <li>- 제 5 조 권 한</li>\r\n");
      out.write("    <li>- 제 6 조 의 무</li>\r\n");
      out.write("    <li>- 제 7 조 직 무</li>\r\n");
      out.write("    <li>- 제 8 조 인사상 불이익처우 금지</li>\r\n");
      out.write("    <li>- 제 9 조 회사의 지원</li>\r\n");
      out.write("    <li>- 제10조 전담부서</li>\r\n");
      out.write("</ul>\r\n");
      out.write("<ul>\r\n");
      out.write("    <li><a href=\"#tit03\">3. 제3장 자율준수협의회</a></li>\r\n");
      out.write("    <li>- 제 11 설치 및 구성</li>\r\n");
      out.write("    <li>- 제 12 조 역 할</li>\r\n");
      out.write("    <li><a href=\"#tit04\">4. 제4장 임직원의 의무</a></li>\r\n");
      out.write("    <li>- 제 13 의 무</li>\r\n");
      out.write("    <li><a href=\"#tit05\">5. 제5장 자율준수프로그램의 운명</a></li>\r\n");
      out.write("    <li>- 제 14 설치 및 구성</li>\r\n");
      out.write("    <li>- 제15조 교육프로그램의 실시</li>\r\n");
      out.write("    <li>- 제16조 모니터링제도</li>\r\n");
      out.write("    <li>- 제17조 경쟁법 위반 임직원에 대한 제재 등</li>\r\n");
      out.write("    <li>- 제18조 문서관리</li>\r\n");
      out.write("    <li>- 제19조 운영성과 평가</li>\r\n");
      out.write("    <li>- 제20조 운영현황의 공개</li>\r\n");
      out.write("    <li>- 제21조 기타</li>\r\n");
      out.write("    <li>- 제 14 설치 및 구성</li>\r\n");
      out.write("</ul>\r\n");
      out.write("</div>\r\n");
      out.write("<div>\r\n");
      out.write("<p><img alt=\"목차\" src=/></p>\r\n");
      out.write("<p>제 1조 시행시기</p>\r\n");
      out.write("<h5 id=\"tit01\">1. 제 1 장 총 칙</h5>\r\n");
      out.write("<ul>\r\n");
      out.write("    <li>- 제 1 조 목 적<br />\r\n");
      out.write("    본 규정은 임직원들의 경쟁법 준수를 위해 도입한 공정거래 자율준수 프로그램의 합리적 운영 및 실천을 위해 필요한 사항을 정하는 데 그 목적이 있다.</li>\r\n");
      out.write("    <li>- 제 2 조 (적용범위)<br />\r\n");
      out.write("    본 규정은 근무지역이나 고용형태에 관계없이 아시아나항공 주식회사에 재직중인 모든 임직원에게 적용된다.</li>\r\n");
      out.write("    <li>- 제 3 조 (용어의 정의) <br />\r\n");
      out.write("    본 규정에서 사용하는 용어는 다음과 같이 정의한다.<br />\r\n");
      out.write("    1) '자율준수'는 회사에 적용되는 경쟁 관련 법령, 규정의 내용을 자율적으로 충족시키는 것을 말한다.</li>\r\n");
      out.write("    <li>2) '경쟁법'은 공정거래법, 약관의 규제에 관한 법률, 하도급거래 공정화에 관한 법률, 방문판매 등에 관한 법률, 표시＊광고의 <br />\r\n");
      out.write("    공정화에 관한 법률, 할부거래에 관한 법률 등 경쟁의 촉진 및 공정거래질서의 유지를 목적으로 제정된 제반법규를 말한다.</li>\r\n");
      out.write("    <li>3) '경쟁당국'은 공정거래위원회를 비롯 경쟁법의 집행에 직간접적으로 관여하는 행정기관을 의미한다.</li>\r\n");
      out.write("    <li>4) '자율준수관리자'는 자율준수 프로그램의 운영을 총괄하는 자를 말한다.</li>\r\n");
      out.write("</ul>\r\n");
      out.write("<h5 id=\"tit02\">2. 제 2 장 자율준수관리자</h5>\r\n");
      out.write("<ul>\r\n");
      out.write("    <li>- 제 4 조 (선임과 해임)</li>\r\n");
      out.write("    <li>1) 자율준수 프로그램의 적정한 운영을 위하여 대표이사는 이사회 결의를 거쳐 자율준수관리자를 선임하거나, 법무업무를 직접 <br />\r\n");
      out.write("    관할하는 임원으로 하여금 자율준수관리자의 직무를 행하게 할 수 있다.</li>\r\n");
      out.write("    <li>2) 대표이사는 자율준수관리자가 경쟁법 위반행위에 관여되어 있어 더 이상 직무를 수행하는 것이 부적합하다고 판단되는 경우 <br />\r\n");
      out.write("    자율준수관리자의 지위에서 해임할 수 있다.</li>\r\n");
      out.write("    <li>- 제 5 조 (권 한)<br />\r\n");
      out.write("    자율준수관리자는 다음 각 호의 권한을 행사할 수 있다. <br />\r\n");
      out.write("    1) 자율준수 실태에 대한 점검, 조사권 <br />\r\n");
      out.write("    2) 경쟁법을 위반한 사항에 대한 개선, 시정요구권 <br />\r\n");
      out.write("    3) 직무를 수행함에 있어서 필요한 자료 및 정보의 제출요구권 <br />\r\n");
      out.write("    4) 기타 이사회가 필요하다고 인정하는 권한</li>\r\n");
      out.write("    <li>- 제 6 조 (의 무)<br />\r\n");
      out.write("    자율준수관리자는 자율준수 프로그램의 지속적인 실천 및 정착을 위해 노력하여야 하며, 프로그램 운영중 문제점<br />\r\n");
      out.write("    을 발견한 경우에는 개선에 필요한 조치를 취하여야 한다.</li>\r\n");
      out.write("    <li>- 제 7 조 (직 무)<br />\r\n");
      out.write("    자율준수관리자는 자율준수 프로그램의 효율적 운영을 위하여 다음 각 호의 직무를 수행한다.<br />\r\n");
      out.write("    1. 자율준수 프로그램의 운영<br />\r\n");
      out.write("    2. 자율준수 프로그램과 관련된 세부계획의 수립<br />\r\n");
      out.write("    3. 자율준수 실태 점검을 위한 감사계획의 수립 및 실시<br />\r\n");
      out.write("    4. 모니터링 결과의 평가 및 위반자에 대한 제재요구<br />\r\n");
      out.write("    5. 경쟁법을 위반하거나 위반의 우려가 있는 사안에 대한 개선 및 시정요구<br />\r\n");
      out.write("    6. 자율준수규정에 대한 임직원 교육<br />\r\n");
      out.write("    7. 자율준수 행동강령의 제정 및 운영<br />\r\n");
      out.write("    8. 자율준수 활동결과에 대한 기록유지<br />\r\n");
      out.write("    9. 자율준수 활동계획과 활동상황을 사장에게 보고<br />\r\n");
      out.write("    10. 경쟁당국 등과의 협조 및 지원<br />\r\n");
      out.write("    11. 기타 자율준수 프로그램의 운영을 위하여 필요하다고 인정하는 사항</li>\r\n");
      out.write("    <li>- 제 8 조 (인사상 불이익 처우 금지)<br />\r\n");
      out.write("    회사는 업무집행의 객관성, 독립성 확보를 위하여 당해 업무수행과 관련된 사유로 자율준수관리자에게 인사상의<br />\r\n");
      out.write("    불이익을 부과하여서는 아니된다.</li>\r\n");
      out.write("    <li>- 제 9 조 (회사의 지원)<br />\r\n");
      out.write("    ① 회사는 자율준수관리자의 효율적인 업무수행에 필요한 인적, 물적 자원을 적극적으로 지원하여야 한다.<br />\r\n");
      out.write("    ② 자율준수관리자는 회사의 비용으로 전문가의 조력을 구할 수 있다.</li>\r\n");
      out.write("</ul>\r\n");
      out.write("<h5 id=\"tit03\">3. 제 3 장 자율준수협의회</h5>\r\n");
      out.write("<ul>\r\n");
      out.write("    <li>- 제11조 (설치 및 구성)</li>\r\n");
      out.write("    <li>① 자율준수관리자는 자문기구로서 영업, 마케팅, 구매, 광고, 하도급 등과 관련이 있는 부서의 장으로 구성된 자율<br />\r\n");
      out.write("    준수협의회를 설치, 운영할 수 있다.</li>\r\n");
      out.write("    <li>② 자율준수협의회 의장은 자율준수관리자로 한다.</li>\r\n");
      out.write("    <li>③ 자율준수협의회 구성원은 사안에 따라 자율준수관리자가 지정할 수 있다.</li>\r\n");
      out.write("    <li>- 제12조 (역 할)<br />\r\n");
      out.write("    자율준수협의회는 자율준수 프로그램을 운영함에 있어 나타나거나 나타날 수 있는 각종 문제점들을 논의하고, 이<br />\r\n");
      out.write("    를 보완, 개선하기 위한 방안을 협의하며, 필요시 대표이사에게 회사의 관련 규정 변경 및 업무관행에 대한 개선을<br />\r\n");
      out.write("    요청할 수 있다.</li>\r\n");
      out.write("</ul>\r\n");
      out.write("<h5 id=\"tit04\">4. 제 4 장 임직원의 의무</h5>\r\n");
      out.write("<ul>\r\n");
      out.write("    <li>- 제13조 (의 무)</li>\r\n");
      out.write("    <li>① 모든 임직원은 경쟁법을 준수하여야 한다.</li>\r\n");
      out.write("    <li>② 임직원은 업무수행을 함에 있어 경쟁법에 위반될 가능성이 있다고 판단되는 경우 자율준수관리자 또는 법무팀<br />\r\n");
      out.write("    과 협의하여야 한다.</li>\r\n");
      out.write("    <li>③ 업무수행을 함에 있어 경쟁법 위반사실을 발견하거나 위반가능성을 발견한 임직원은 이를 지체없이 자율준수관<br />\r\n");
      out.write("    리자 또는 법무팀에 보고하여야 한다.</li>\r\n");
      out.write("</ul>\r\n");
      out.write("<h5 id=\"tit05\">5. 제 5 장 자율준수 프로그램의 운영</h5>\r\n");
      out.write("<ul>\r\n");
      out.write("    <li>제14조 (자율준수편람)</li>\r\n");
      out.write("    <li>① 자율준수관리자는 임직원들의 경쟁법 위반사례를 예방하고 관련 법령에 대한 이해를 돕기 위하여 자율준수편람<br />\r\n");
      out.write("    을 제작, 배포할 수 있다.</li>\r\n");
      out.write("    <li>② 자율준수편람은 회사의 조직과 특성에 맞게 작성하여야 한다.</li>\r\n");
      out.write("    <li>③ 관계법령 및 규정 등의 변경이 있을 때에는 관련내용을 지체없이 자율준수편람에 반영하여야 한다.</li>\r\n");
      out.write("    <li>- 제15조 (교육프로그램의 실시)<br />\r\n");
      out.write("    1. 관계법령 및 규정 등의 변경이 있을 때에는 관련내용을 지체없이 자율준수편람에 반영하여야 한다.</li>\r\n");
      out.write("    <li>2. 자율준수관리자는 영업, 마케팅, 구매, 광고, 하도급 등 경쟁법 위반의 가능성이 높은 직무에 종사하는 임직원을<br />\r\n");
      out.write("    대상으로 특별교육을 실시할 수 있다.</li>\r\n");
      out.write("    <li>3. 자율준수관리자는 교육내용에 대한 평가를 실시할 수 있으며, 필요시 그 결과를 인사고과에 반영할 것을 관련부<br />\r\n");
      out.write("    서에 요청할 수 있다</li>\r\n");
      out.write("    <li>4. 자율준수교육에 관한 필요한 세부사항은 자율준수관리자가 별도로 정할 수 있다.<br />\r\n");
      out.write("    즉시 시행한다.</li>\r\n");
      out.write("    <li>- 제16조 (모니터링제도)<br />\r\n");
      out.write("    자율준수관리자는 다음 각 호의 1에 해당하는 방법에 의하여 자율준수 프로그램의 준수 여부를 연1회 이상 확인하<br />\r\n");
      out.write("    여 대표이사에게 보고하여야 한다.<br />\r\n");
      out.write("    ① 임직원의 자율준수실태 등에 대한 점검, 조사<br />\r\n");
      out.write("    ② 자율준수관리자의 요구에 의하여 각 부서별로 작성한 각종 체크리스트의 검토 및 확인<br />\r\n");
      out.write("    ③ 자율준수관리자의 요구에 의하여 제출된 신고서, 보고서, 각종 자료의 검토 및 확인</li>\r\n");
      out.write("    <li>- 제17조 (경쟁법 위반 임직원 등에 대한 제재 등)<br />\r\n");
      out.write("    자율준수관리자는 다음 각 호의 1에 해당하는 방법에 의하여 자율준수 프로그램의 준수 여부를 연1회 이상 확인하<br />\r\n");
      out.write("    여 대표이사에게 보고하여야 한다.<br />\r\n");
      out.write("    ① 자율준수관리자는 경쟁법을 위반한 임직원에 대해서는 위반의 정도에 따라 징계를 요구할 수 있다.</li>\r\n");
      out.write("    <li>② 자율준수관리자는 경쟁법을 위반한 것으로 판단되거나 위반의 우려가 있는 사안에 대하여 관련 부서장에게 변<br />\r\n");
      out.write("    경 또는 시정을 요청할 수 있으며, 요청을 받은 경우 관련 부서장은 이에 따라야 한다.</li>\r\n");
      out.write("    <li>- 제18조 (문서관리)</li>\r\n");
      out.write("    <li>① 임직원에 대한 교육 및 모니터링 활동, 위반자에 대한 제재 등 자율준수 프로그램을 운영함에 있어 요구되는 주<br />\r\n");
      out.write("    요 문서들은 자율준수관리자의 책임하에 분류되고 보관되어야 한다.</li>\r\n");
      out.write("    <li>② 자율준수관리자는 전1항의 문서 이외에도 자율준수프로그램의 운영에 관한 주요 문서들을 유지, 보관할 수 있<br />\r\n");
      out.write("    도록 조치하여야 한다.</li>\r\n");
      out.write("    <li>- 제19조 (운영성과 평가)</li>\r\n");
      out.write("    <li>① 자율준수관리자는 자율준수프로그램이 효과적으로 작동되고 있는지를 주기적으로 점검하여야 하며, 발견된 문<br />\r\n");
      out.write("    제점 및 원인에 대해서는 개선방안과 함께 이를 대표이사에게 보고하여야 한다.</li>\r\n");
      out.write("    <li>② 자율준수관리자는 필요시 자율준수프로그램 운영실태에 대한 종합점검 및 개선점을 파악하기 위하여 외부 관계<br />\r\n");
      out.write("    기관의 평가를 신청할 수 있다.</li>\r\n");
      out.write("    <li>- 제20조 (운영현황의 공개)<br />\r\n");
      out.write("    회사는 회사 홈페이지나 사내 통신망(텔레피아)을 통해 전 임직원이 자율준수 프로그램 운영현황을 알 수 있도록<br />\r\n");
      out.write("    조치하여야 한다.</li>\r\n");
      out.write("    <li>- 제21조 (기 타)<br />\r\n");
      out.write("    자율준수관리자는 본 규정을 운영함에 있어 필요한 세부사항에 대하여는 관계부서와 협의하여 별도의 규정을 제정,<br />\r\n");
      out.write("    시행할 수 있다.</li>\r\n");
      out.write("</ul>\r\n");
      out.write("<p>부칙</p>\r\n");
      out.write("<p>제 1 조 (시행시기) 이 규정은 2002년 7월 2일부터 시행한다.</p>\r\n");
      out.write("<p>부칙</p>\r\n");
      out.write("<p>제 1 조 (시행시기) 이 규정은 2011년 1월 1 일부터 시행한다.</p>\r\n");
      out.write("<p>부칙</p>\r\n");
      out.write("<p>제 1 조 (시행시기) 이 규정은 공포일로부터 즉시 시행한다.</p>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<form name=\"agree\" method=\"post\" action=\"agree.action\">\r\n");
      out.write("<div>이용약관에 동의합니다. <input type=\"checkbox\" name=\"agree\"></div>\r\n");
      out.write("<input type=\"button\" value=\"약관 동의\" onClick=\"test()\" >\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("            <!-- //내용 -->\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- //contentG_w -->\r\n");
      out.write("\r\n");
      out.write("            <hr />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("         </div>\r\n");
      out.write("         <!-- //contentG -->\r\n");
      out.write("         </div>\r\n");
      out.write("      <!-- //containerG_w -->\r\n");
      out.write("\r\n");
      out.write("   </div>\r\n");
      out.write("   <!-- //wrapG -->\r\n");
      out.write("</div>\r\n");
      out.write("<!-- //wrapG_all -->\r\n");
      out.write("\r\n");
      out.write("<hr />\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/inc/footer.jsp", out, true);
      out.write("\r\n");
      out.write(" \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
