/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.67
 * Generated at: 2015-12-25 07:44:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.membership;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class joinInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/inc/header1.jsp", out, true);
      out.write("\r\n");
      out.write("<title>MIRACLE AIR &gt; 대메뉴 &gt; 중메뉴 &gt; 소메뉴</title>\r\n");
      out.write("<script>\r\n");
      out.write("function nullCheck(){\r\n");
      out.write("\tvar id = document.getElementById(\"id\");\r\n");
      out.write("\tvar pw = document.getElementById(\"password\");\r\n");
      out.write("\tvar pwConf = document.getElementById(\"password_confirm\");\r\n");
      out.write("\tvar name = document.getElementById(\"name\");\r\n");
      out.write("\tvar birth = document.getElementById(\"birth\");\r\n");
      out.write("\tvar email = document.getElementById(\"email\");\r\n");
      out.write("\tvar add = document.getElementById(\"address\");\r\n");
      out.write("\tvar nation = document.getElementById(\"nation\");\r\n");
      out.write("\tvar cell = document.getElementById(\"phone\");\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t//alert(id.value+pw.value+pwConf.value+name.value+birth.value+email.value+add.value+nation.value+cell.value);\r\n");
      out.write("\tif(id == null ||id == undefined || id.value ==\"\"){\r\n");
      out.write("\t\talert(\"아이디를  입력해주세요\");\r\n");
      out.write("\t}\r\n");
      out.write("\telse if((pw == null ||pw == undefined ||pw.value ==\"\")  \r\n");
      out.write("\t\t\t|| (pwConf == null ||pwConf == undefined ||pwConf.value ==\"\")){\r\n");
      out.write("\t\talert(\"비밀번호를 입력해주세요\")\r\n");
      out.write("\t}\r\n");
      out.write("\telse if(name == null  ||name == undefined ||name.value ==\"\"){\r\n");
      out.write("\t\talert(\"이름을 입력해주세요\")\r\n");
      out.write("\t}\r\n");
      out.write("\telse if(birth == null  ||birth == undefined ||birth.value ==\"\"){\r\n");
      out.write("\t\talert(\"생년 월일 을 입력해주세요\")\r\n");
      out.write("\t}\r\n");
      out.write("\telse if(email == null ||email == undefined ||email.value ==\"\"){\r\n");
      out.write("\t\talert(\"이메일을 입력해주세요\")\r\n");
      out.write("\t}\r\n");
      out.write("\telse if(add == null ||add == undefined ||add.value ==\"\"){\r\n");
      out.write("\t\talert(\"주소를 입력해주세요\")\r\n");
      out.write("\t}\r\n");
      out.write("\telse if(nation == null ||nation == undefined ||nation.value ==\"\"){\r\n");
      out.write("\t\talert(\"국가를 입력해주세요\")\r\n");
      out.write("\t}\r\n");
      out.write("\telse if(cell == null ||cell == undefined ||cell.value ==\"\"){\r\n");
      out.write("\t\talert(\"전화번호를 입력해주세요\")\r\n");
      out.write("\t}\r\n");
      out.write("\telse{\r\n");
      out.write("\t\tif(pwCheck() && emailCheck())\r\n");
      out.write("\t\tdocument.join.submit();\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function pwCheck(){\r\n");
      out.write("\tvar pw = document.getElementById(\"password\");\r\n");
      out.write("\tvar pwConf = document.getElementById(\"password_confirm\")\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\tif(pw.value.length <= 6 ){\r\n");
      out.write("\t\talert(\"비밀번호는 6자 이상을 입력해주세요\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\telse if(pw.value != pwConf.value){\r\n");
      out.write("\t\talert(\"비밀번호가 다릅니다\")\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\treturn true;\r\n");
      out.write("}\r\n");
      out.write("function emailCheck(){\r\n");
      out.write("\tvar email = document.getElementById(\"email\");\r\n");
      out.write("\tvar format  = /^([\\w-]+(?:\\.[\\w-]+)*)@((?:[\\w-]+\\.)*\\w[\\w-]{0,66})\\.([a-z]{2,6}(?:\\.[a-z]{2})?)$/;\r\n");
      out.write("\t\r\n");
      out.write("\tif(email.value.search(format)==-1){\r\n");
      out.write("\t\talert(\"이메일 형식에 맞게 입력해 주세요\");\r\n");
      out.write("\t\t$(\"#email\").focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\treturn true;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/inc/header2.jsp", out, true);
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"sub\">\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/inc/header2_1.jsp", out, true);
      out.write("\r\n");
      out.write("   <!-- gnb -->\r\n");
      out.write(" ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/inc/gnb.jsp", out, true);
      out.write(" \r\n");
      out.write("   <!-- //gnb -->\r\n");
      out.write("\r\n");
      out.write("      <hr />\r\n");
      out.write("\r\n");
      out.write("   <!-- containerG_w -->\r\n");
      out.write("   <div id=\"containerG_w\" class=\"sub01\">      \r\n");
      out.write("      <h2 class=\"blind\">본문 영역</h2>\r\n");
      out.write("\r\n");
      out.write("         <!-- //contentG_title -->\r\n");
      out.write("\r\n");
      out.write("      <h3 class=\"blind\">시설현황</h3>\r\n");
      out.write("\r\n");
      out.write("      <!-- contentG -->\r\n");
      out.write("      <div id=\"contentG\">\r\n");
      out.write("\r\n");
      out.write("         <!-- 본문영역 -->\r\n");
      out.write("         <div id=\"contentG_w\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <!-- 내용 -->\r\n");
      out.write("<form action=\"joinCheck.action\" method=\"post\" class=\"join\" name=\"join\">\r\n");
      out.write("\t\t<h2>회원가입<br/><br/><br/></h2>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<label for=\"inputId\">아이디</label> \r\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"id\" name=\"id\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<label for=\"inputPassword\">비밀번호</label>\r\n");
      out.write("\t\t\t\t<input type=\"password\"  id=\"password\" name=\"password\" placeholder=\"비밀번호\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<label for=\"inputConfirPw\">비밀번호 확인</label> \r\n");
      out.write("\t\t\t\t<input type=\"password\" id=\"password_confirm\" id=\"password_confirm\" name=\"password_confirm\" placeholder=\"비밀번호 확인\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<label for=\"inputName\">이름</label> <input type=\"text\" id=\"name\" name=\"name\" placeholder=\"이름\" >\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<label for=\"inputBirth\">생년 월 일</label> <input type=\"text\" id=\"birth\" name=\"birth\" placeholder=\"0000-00-00\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<label for=\"inputEmail\">이메일</label> <input type=\"email\" id=\"email\" name=\"email\" placeholder=\"이메일\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<label for=\"inputAddress\">주소</label> <input type=\"text\" id=\"address\" name=\"address\" placeholder=\"주소\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<label for=\"inputNation\">국가</label> <input type=\"text\" id=\"nation\" name=\"nation\" placeholder=\"국가\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<label for=\"inputPhone\">phone</label> <input type=\"text\" id=\"phone\" name=\"phone\" placeholder=\"전화번호\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<label for=\"inputName\"></label>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"확인\" onclick=\"nullCheck()\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write("            <!-- //내용 -->\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- //contentG_w -->\r\n");
      out.write("\r\n");
      out.write("            <hr />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("         </div>\r\n");
      out.write("         <!-- //contentG -->\r\n");
      out.write("         </div>\r\n");
      out.write("      <!-- //containerG_w -->\r\n");
      out.write("\r\n");
      out.write("   </div>\r\n");
      out.write("   <!-- //wrapG -->\r\n");
      out.write("</div>\r\n");
      out.write("<!-- //wrapG_all -->\r\n");
      out.write("\r\n");
      out.write("<hr />\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/inc/footer.jsp", out, true);
      out.write("\r\n");
      out.write(" \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
