/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.67
 * Generated at: 2015-12-25 02:23:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/inc/footer.jsp", Long.valueOf(1450785454000L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/Air/css/import.css\" />\r\n");
      out.write("<script src=\"/Air/js/jquery-1.11.2.min.js\"></script>\r\n");
      out.write("<script src=\"/Air/js/TweenMax.min.js\"></script>\r\n");
      out.write("<script src=\"/Air/js/common.libs.js\"></script>\r\n");
      out.write("<script src=\"/Air/js/jquery.ListBox.js\"></script>\r\n");
      out.write("<script src=\"/Air/js/core.js\"></script>\r\n");
      out.write("<script src=\"/Air/js/opacity.slide.js\"></script>\r\n");
      out.write("<script src=\"/Air/js/hb.accordion.slide.js\"></script>\r\n");
      out.write("<script src=\"/Air/js/common.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<title>MIRACLEAIR</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"skip\">\r\n");
      out.write("\t\t<a href=\"#container\">본문 바로가기</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"wrapper\">\r\n");
      out.write("\t\t<div class=\"header\">\r\n");
      out.write("\t\t\t<div class=\"header-container\">\r\n");
      out.write("\t\t\t\t<h1>\r\n");
      out.write("\t\t\t\t\t<a href=\"index.action\"><img src=\"/Air/img/main/logo.png\" alt=\"MIRACLEAIR\" /></a>\r\n");
      out.write("\t\t\t\t</h1>\r\n");
      out.write("\t\t\t\t<aside class=\"header-side\">\r\n");
      out.write("\t\t\t\t\t<div class=\"header-side-container\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"webshow\">\r\n");
      out.write("\t\t\t\t\t\t\t<li id=\"loginli\"><a href=\"membershipLogin.action\">로그인</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li id=\"logoutli\" style=\"display: none;\"><a href=\"\">로그아웃</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"membership.action\">회원가입</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\"\t>마일리지</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</aside>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"header-gnb\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"header-menu\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<nav class=\"gnb\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a class=\"menu\" href=\"\">항공권 예매</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"\">국내선 항공권</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"\">국제선 항공권</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a class=\"menu\" href=\"\">여행 가이드</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"\">도시 가이드</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"\">테마 가이드</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a class=\"menu\" href=\"\">여행 에세이</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"\">여행 에세이</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"\">포토 에세이</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a class=\"menu\" href=\"\">커뮤니티</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"\">공지사항</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"\">이벤트</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"\">Q&#38;A</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a class=\"menu\" href=\"\">마이페이지</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"\">회원정보 수정</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"\">예약 관리</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"\">항공권 조회</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- //header-gnb -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- //header-container -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- //header -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //wrapper -->\r\n");
      out.write("\t<hr />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<iframe src=\"if_main.jsp\" frameborder=\"0\" width=\"100%\" height=\"1660\"\tmarginwidth=\"0\" marginheight=\"0\" scrolling=\"no\"></iframe>\r\n");
      out.write("\r\n");
      out.write("<hr />\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("<!-- footer_w -->\r\n");
      out.write("<div id=\"footer_w\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t<h2 class=\"blind\">하단 영역</h2>\r\n");
      out.write("\t\r\n");
      out.write("\t<ul class=\"f_menu\">\r\n");
      out.write("\t\t<li><a href=\"#\">개인정보처리방침</a></li>\r\n");
      out.write("\t\t<li><a href=\"#\">법적고지</a></li>\r\n");
      out.write("\t\t<li><a href=\"#\">이용약관</a></li>\r\n");
      out.write("\t\t<li><a href=\"#\">이메일무단수집거부</a></li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("\t\r\n");
      out.write("\t<h3 class=\"blind\">주소 및 카피라이트</h3>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"footer\">\r\n");
      out.write("\t\t<div class=\"copy_w\">\t\t\t\r\n");
      out.write("\t\t\t<p class=\"logo\">MIRACLE AIR</p>\r\n");
      out.write("\t\t\t<p class=\"address\">세종특별자치시 도움4로 9 사업자 등록번호: 1017-2015-7101 전화: 1577-0606</p>\r\n");
      out.write("\t\t\t<p class=\"copy\">ⓒ 2015 MIRACLE AIR. ALL RIGHTS RESERVED.</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //footer -->\r\n");
      out.write("</div>\r\n");
      out.write("<!-- //footer_w -->");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
